### ISSUE TITLE
.env variable parsed differently than shell exported variable

### ISSUE THREAD

**Issue by andreafspeziale** [nestjs/config#1029]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I jumped into a strange case in which using `ConfigModule` along with `Joi` an env variable is parsed differently if set in the `.env` file or is exported like it would be in a remote deployed env (`export MY_ENV=<value>`)

### Minimum reproduction code

https://github.com/andreafspeziale/env-issue-sample

### Steps to reproduce

Everything in the minimum reproduction code repository README

### Expected behavior

Getting the same value for an env var set in the `.env` file or exported using the shell

### Package version

2.1.0

### NestJS version

8.4.7

### Node.js version

18.5.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, report this issue in the dotenv repository https://github.com/motdotla/dotenv
