### ISSUE TITLE
Allow extending configuration source

### ISSUE THREAD

**Issue by 5d-jh** [nestjs/config#1037]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Our project need to fetch configurations from different sources, like config server, argument variable, etc..

Hence we need to create different class/methods to get configurations based on different source.

### Describe the solution you'd like

Allowing writing custom configuration source.

### What is the motivation / use case for changing the behavior?

Doing so, not only `ConfigService` fetches from `.env` file and environment variable, but can also get config from cloud config and other sources via single interface.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
