### ISSUE TITLE
Validation bug when using an array with envFilePath

### ISSUE THREAD

**Issue by jvalrog** [nestjs/config#1088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I configure the module like this:

```
ConfigModule.forRoot({
      envFilePath: ['.env.development', '.env.staging', '.env.production'],
      isGlobal: true,
      cache: true,
      validationSchema: appConfigSchema,
      validationOptions: {
        abortEarly: true,
      },
    })
```

I already have the 3 .env files and removed a variable from the first one: *.env.development*.

The bug is that the missing variable is not detected by the validation schema, where it's required by Joi, because it's being readed from the next file: *.env.staging*.

If I use a single file then validation works and throws an error.

After looking at the `ConfigModule.loadEnvFile` code I found that after reading the first file, the for-loop still continues, filling/assigning all the missing fields from one file with the next files.

```
for (const envFilePath of envFilePaths) {
      if (fs.existsSync(envFilePath)) {
        config = Object.assign(
          dotenv.parse(fs.readFileSync(envFilePath)),
          config,
        );
        if (options.expandVariables) {
          const expandOptions: DotenvExpandOptions = typeof options.expandVariables === 'object' ? options.expandVariables : {};
          config = expand({ ...expandOptions, parsed: config }).parsed || config;
        }
      }
    }
```

I think there should be a **break** inside the if-statement to avoid reading the next file. Because validation is useless as of now in this scenario, because the result config is a combination of all the files.

### Minimum reproduction code

-

### Steps to reproduce

1. Have several env files in *envFilePath*
2. Remove a Joi required variable from the first file that is read
3. Variable must be present in the rest of files
4. Start the project

### Expected behavior

loadEnvFile should stop processing env files after it reads the first one, so validationSchema works as intended.

### Package version

8.1.1

### NestJS version

8.1.1

### Node.js version

16.17.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
> I think there should be a break inside the if-statement to avoid reading the next file. 

I'm pretty srure that that's not the expected behavior. so changing that will introduces breaking changes.

**Comment by jvalrog** [comment]
> > I think there should be a break inside the if-statement to avoid reading the next file.
> 
> that's not the expected behavior. so changing that would introduce breaking changes.

You're right, for some reason I skiped that line in the documentation. I've changed my code to fix this issue.
Thanks!
