### ISSUE TITLE
.env file loaded even when envFilePath is different while using Prisma

### ISSUE THREAD

**Issue by oliviervanbulck** [nestjs/config#1090]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

When .env.development is set as envFilePath and .env file exists as well, the .env file is loaded instead of .env.development
This happens when prisma is used in the nest project and loaded.

### Minimum reproduction code

https://github.com/oliviervanbulck/nest-env-test

### Steps to reproduce

1. Import ConfigModule

ConfigModule.forRoot({
  isGlobal: true,
  envFilePath: '.env.development', // `.env.${process.env.NODE_ENV}`,
}),

2. Install prisma and create PrismaService
3. Create .env and .env.development
4. Start application and see which variables are loaded

### Expected behavior

.env.development would be read and used for configuration

### Package version

2.2.0

### NestJS version

9.1.4

### Node.js version

16.15.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
Please provide a [minimum reproduction repository](https://jmcdo29.github.io/wtf-is-a-minimum-reproduction).

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by oliviervanbulck** [comment]
I added a reproduction. It happens when using prisma, it seems to override the basic configuration of @nestjs/config.

**Comment by oliviervanbulck** [comment]
But the ConfigModule is isolated from process.env after initializing, or not? Isn't it possible to load the given envFilePath with the precise file and save the values in that module, before prisma loading the other .env file over process.env?

EnvFilePath should always be the right place, no matter what other packages are doing imo?

**Comment by jmcdo29** [comment]
You can set `ignoreEnvVars` to ignore values already populated in `process.env` and only use what's read in the `.env` files you define

https://github.com/nestjs/config/blob/master/lib/interfaces/config-module-options.interface.ts#L26

**Comment by oliviervanbulck** [comment]
> You can set `ignoreEnvVars` to ignore values already populated in `process.env` and only use what's read in the `.env` files you define
> 
> https://github.com/nestjs/config/blob/master/lib/interfaces/config-module-options.interface.ts#L26

Oh thanks! I thought I tried that, but apparently not.
