### ISSUE TITLE
TRAILING WHITE SPACES IN ENVFILEPATH PREVENTS .ENV FROM BEING PARSED INTO CONFIGMODULE

### ISSUE THREAD

**Issue by anjolaoluwaakindipe** [nestjs/config#1093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

``` javascript
import { Module } from '@nestjs/common';
import { ConfigModule } from '@nestjs/config';

import { appConfiguration } from './config';
import { configValidation } from './config.validationSchema';

@Module({
  imports: [
    ConfigModule.forRoot({
      envFilePath: ['.env.development '], // <---- white space at the end of .env.development
      cache: true,
      load: [appConfiguration],
      isGlobal: true,
      validationSchema: configValidation,
    }),
  ],
  exports: [ConfigModule],
})
export class AppConfig {}
```
.env.development does not get parsed into ConfigModule due to the white space at the end.

### Minimum reproduction code

N/A

### Expected behavior

If it is just white spaces at the end of the file path the code should still be able to work. I was using validationSchema with Joi and I I got validation errors from the .required() function. It took me 30 minutes to realize this.  

### Package version

2.2.0

### NestJS version

9.0.0

### Node.js version

v16.13.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
If you said that the file is called `foo.env ` then the lib should look up for it. I don't think we need to change that

What we could do instead is raise an exception if the file was not found.

**Comment by micalevisk** [comment]
as you can see below, we just ignore those files that were not found

https://github.com/nestjs/config/blob/fc2fedbe68559a1b47f9c41382b345364eaa3390/lib/config.module.ts#L181-L190

as a feature request, we could have a flag (like: `ignoreNotFound: boolean`; `true` by default) to change that behavior.

**Comment by anjolaoluwaakindipe** [comment]
Okay, I understand, but is it possible to use the envFilePath.trim() method to clear white spaces from the start and end of the text?

**Comment by micalevisk** [comment]
yes but why? files with spaces in the end/start are valid

**Comment by micalevisk** [comment]
instead you should have that in your side:

```
envFilePath: ['.env.development '].map(p => p.trim())
```

**Comment by anjolaoluwaakindipe** [comment]
> yes but why? files with spaces in the end/start in their names are valid

Oh I didn't realize that.

**Comment by anjolaoluwaakindipe** [comment]
> instead you should have that in your side:
> 
> ```
> envFilePath: ['.env.development '].map(p => p.trim())
> ```
I think I'll do this in order to prevent issues like this next time. Thank you!!!

**Comment by micalevisk** [comment]
so I guess you can close this Issue now.

If you want the feature I mentioned earlier, open another issue with the _feature request_ template :smile_cat:
