### ISSUE TITLE
[Bug] Upgrade dotenv-expand version to avert .env vars interpolation issue

### ISSUE THREAD

**Issue by avmaxim** [nestjs/config#1172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The latest version of `@nestjs/config` package (`2.2.0`) uses `dotenv-expand@8.0.3` library as a dependency with a strict version. This **version** (`8.0.3`) is **out-of-date** and has a prevalent issue raised on Github - https://github.com/motdotla/dotenv-expand/issues/65. Based on that, the error is thrown in case an ENV variable contains an uninterpolated `$` sign in it like in the example:
> TOKEN ="abcd$1234"

that leads up to:

<img width="748" alt="image" src="https://user-images.githubusercontent.com/9191544/215841243-d9701a03-6436-421e-b645-03fd5b049e81.png">

In a newer version of this library `v10.0.0` they changed an interpolation algo that should resolve the `$` sign use case above - [see details](https://github.com/motdotla/dotenv-expand/blob/v10.0.0/lib/main.js).

Thus the motivation behind this issue is to upgrade `dotenv-expand` in the `@nestjs/config` package to the latest version to prevent such an issue and keep all nestjs packages up-to-speed.

### Minimum reproduction code

https://github.com/motdotla/dotenv-expand/blob/v8.0.3/lib/main.js

### Expected behavior

The `@nestjs/config` package supports the latest version of `dotenv-expand` lib and **does not fail** even tho ENV variables contain uninterpolated dollar signs.

### Package version

2.2.0

### NestJS version

9.1.4

### Node.js version

14.19.0

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by micalevisk** [comment]
this should be fixed by PR #1136

**Comment by avmaxim** [comment]
> this should be fixed by PR #1136

@micalevisk sounds great! thank you! do you have any upcoming plans to merge it to the master?

**Comment by micalevisk** [comment]
We don't have any ETA

---

I'm bit concern on something: as that is a major upgrade to `dotenv-expand`, can we really bring it in the next patch bump of `@nestjs/config`? 🤔 I didn't checked out yet what are the breaking changes from v8 to v10
