### ISSUE TITLE
Support for remote config

### ISSUE THREAD

**Issue by juzerali** [nestjs/config#1211]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I did not find a good way of managing configuration remotely with NestJS server

### Describe the solution you'd like

Provide support for loading config from a [Spring Cloud Config](https://docs.spring.io/spring-cloud-config/docs/current/reference/html/) server

### Teachability, documentation, adoption, migration strategy

Spring Cloud config works with a wide variety of config backends. Most of the stuff is documented in the official documentation

### What is the motivation / use case for changing the behavior?

Remote config is a must.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
