### ISSUE TITLE
Can't use envFilePath

### ISSUE THREAD

**Issue by tttmaximttt** [nestjs/config#1270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

```
ConfigModule.forRoot({
      isGlobal: true,
      envFilePath: `${process.env.NODE_ENV ? `.${process.env.NODE_ENV}` : ''}.env`,
      load: [defaultConfig],
      validate(config: Record<string, unknown>) {
        const validatedConfig = plainToInstance(
          EnvironmentVariables,
          config,
          { enableImplicitConversion: true }
        )
        const errors = validateSync(validatedConfig, { skipMissingProperties: false })

        if (errors.length > 0) {
          throw new Error(errors.toString())
        }
        return validatedConfig
      }
    })
    
```
    
I have two files `.env` and `.test.env` and when I try to run tests with NODE_ENV=test I still get env vars from `.env` but in `envFilePath` .test.env was passed

### Minimum reproduction code

------------------

### Expected behavior

shoudl load file from envFilePath

### Package version

2.3.1

### NestJS version

9.3.7

### Node.js version

18.15.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
please try hard coding it: `envFilePath: '.test.env'` 

Se if you still got the same behavior

**Comment by tttmaximttt** [comment]
how can I change .env files depending on env?

**Comment by tttmaximttt** [comment]
I tryed to hardcode it, but some how common `.env` file was used not `.test.env`

**Comment by micalevisk** [comment]
I'd say this is not a bug but some other package is loading `.env` while `@nestjs/config` is loading `.test.env` just fine

Are you using Prisma?

---

#### [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by tttmaximttt** [comment]
no, I don't use Prisma

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
