### ISSUE TITLE
Loaded config not validated

### ISSUE THREAD

**Issue by feelgood-interface** [nestjs/config#1311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The loaded configuration (through _load_) is not validated, when using a custom validate function (_validate_) or schema (_validationSchema_). Only environment configuration (global or from _envFilePath_) is validated.

### Minimum reproduction code

https://github.com/feelgood-interface/issue-config-validate

### Steps to reproduce

1. npm i
2. npm run start
3. Validation fails. If validation is removed, the correct config is returned at GET 'localhost:3000'.

### Expected behavior

Configuration must be loaded before validation.

### Package version

2.3.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by feelgood-interface** [comment]
I would expect that it will validate any config that is available through the _ConfigService_, and not only  _environment variables_. So it might not be a bug, but rather a feature.

**Comment by micalevisk** [comment]
yeah, by looking at this:

https://github.com/nestjs/config/blob/2870779c64e76a7e127ab14ca2f110ee93efbdba/lib/config.module.ts#L55
https://github.com/nestjs/config/blob/2870779c64e76a7e127ab14ca2f110ee93efbdba/lib/config.module.ts#L67-L76

we can see that only variables loaded from some dot env file will be taking into account when using that `validationSchema`
