### ISSUE TITLE
Update Type For "propertyPath" params in ConfigService.get

### ISSUE THREAD

**Issue by AndyT2503** [nestjs/config#1327]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I have a **config service model** which is nested object like bellow
```
interface EnvironmentConfiguration {
  database: DatabaseConfiguration;
  listeningPort: number;
}

interface DatabaseConfiguration {
  name: string;
  username: string;
  password: string;
  host: string;
  port: number;
}
```
The we inject `ConfigService<EnvironmentConfiguration>` and use `ConfigService.get`, `propertyPath` just only accept two value are `'database' | 'listeningPort'`. So I can not get value from nested object directly like `ConfigService.get('database.host')` with strict type for `propertyPath`. 

### Describe the solution you'd like

We should create a utility type to flatten object like bellow,
```
type FlattenObject<T extends object> = object extends T ? object : {
  [K in keyof T]-?: (x: NonNullable<T[K]> extends infer V ? V extends object ?
    V extends readonly any[] ? Pick<T, K> : Flatten<V> extends infer FV ? ({
      [P in keyof FV as `${Extract<K, string | number>}.${Extract<P, string | number>}`]:
      FV[P] }) : never : Pick<T, K> : never
  ) => void } extends Record<keyof T, (y: infer O) => void> ?
  O extends infer U ? { [K in keyof O]: O[K] } : never : never
```
Now type of `propertyPath` should change to 
```
propertyPath: KeyOf<FlattenObject<K>> | KeyOf<K>
```

### What is the motivation / use case for changing the behavior?

Currently, `ConfigService.get` accept `propertyPath `with type is `KeyOf<K>`. If we have simple model of config like bellow.
```
interface EnvironmentConfiguration {
  databaseHost: string;
  databasePort: number;
  databaseName: string;
  listeningPort: number;
}
```
Then we inject `ConfigService<EnvironmentConfiguration>` and use `ConfigService.get` to get some value, it work ok. But when I change `EnvironmentConfiguration` to nested object
```
interface EnvironmentConfiguration {
  database: DatabaseConfiguration;
  listeningPort: number;
}

interface DatabaseConfiguration {
  name: string;
  username: string;
  password: string;
  host: string;
  port: number;
}
```
Now, when we inject `ConfigService<EnvironmentConfiguration>` and use `ConfigService.get`, `propertyPath` just only accept two value are `'database' | 'listeningPort'`. If I want get value from nested object directly, I can not use strict type for `propertyPath`. 
So I propose update type for `propertyPath` to `"listeningPort" | "database.name" | "database.username" | "database.password" | "database.host" | "database.port"`. And we can get value from nested object directly with strict type for `propertyPath`.

**Comment by kamilmysliwiec** [comment]
Use `infer: true` https://docs.nestjs.com/techniques/configuration#using-the-configservice
