### ISSUE TITLE
Allow nested properties be overridden by environment variables

### ISSUE THREAD

**Issue by jarias** [nestjs/config#1338]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I use a custom config file or a yaml file to load config properties I can't override those via environment variables if needed, for example in Spring framework if I have a property `database.user` I can override it with an env var `DATABASE_USER`. 

### Describe the solution you'd like

I would like to be able to override nested config properties via environment variables

### What is the motivation / use case for changing the behavior?

NestJS config module allows to override flat properties but not nested, this is confusing to users that expect a functionality be available regardless of the way they choose to have their default properties configures. If for some reason this won't be implemented at least a documentation update should be put in place to avoid confusion.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
