### ISSUE TITLE
ConfigModule with validationSchema does not allow numbers

### ISSUE THREAD

**Issue by jackfiallos** [nestjs/config#1353]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Potential Commit/PR that introduced the regression

efdb29ea998fdf0875277ba4de981c2528238634

### Versions

2.3.2  -> 2.3.3

### Describe the regression

hey @MatthiasKunnen I'm checking this late but now existing applications seems to be broken if we use validationSchema to verify and cast the env vars.

### Minimum reproduction code

for example, an existing application could use something like this:

```
ConfigModule.forRoot({
  validationSchema: Joi.object({
    APP_PORT: Joi.number().description('App Port').default(3000),
  })
})
```

this will make APP_PORT to be undefined because joi is casting this as number, so now after this change (https://github.com/nestjs/config/commit/efdb29ea998fdf0875277ba4de981c2528238634) in order to make it work again the joi validation should be updated to string instead of number.

...
APP_PORT: Joi.string().description('App Port').default(3000), // <- now should be using .string() to be considered
...

but now we're loosing the schemas validation

### Expected behavior

obviously this has introduced a breaking change that probably wasn't considered but the expected behaviour should this:

```
ConfigModule.forRoot({
  validationSchema: Joi.object({
    APP_PORT: Joi.number().description('App Port').default(3000),
  })
})
```

**Comment by iflairritesh** [comment]
Any update on this?
I'am also facing this issue in version 2.3.3.

**Comment by jackfiallos** [comment]
happy to send a PR but first I would like to understand the motivation of this, maybe I'm loosing something!

@iflairritesh if you're having issues, you can still use the previous version (2.3.2) in the meantime we solve this.

**Comment by kamilmysliwiec** [comment]
Fixed in this commit https://github.com/nestjs/config/commit/d2236e6b12ff77c77bdb1f9e732fea6821416aac

Published as 2.3.4

**Comment by MatthiasKunnen** [comment]
The example you provided seems to be working fine for me.

If I'm assuming correctly, you might be using `process.env.APP_PORT` to access the environment variable. 

You should instead be using `configService.get('APP_PORT')`. See <https://docs.nestjs.com/techniques/configuration#using-the-configservice>.

In `main.ts` you can use `app.get(ConfigService).get('APP_PORT')`.

**Comment by iflairritesh** [comment]
Thank you :) Its working now! @kamilmysliwiec

**Comment by jackfiallos** [comment]
@MatthiasKunnen what's you're assuming is almost what I've done but instead I'm using `registerAs` forcing me to have a better structure.

but I can confirm the fix has made the trick, thanks guys
