### ISSUE TITLE
Class based configuration using decorators like @Configuration, @ConfigurationKey

### ISSUE THREAD

**Issue by halilkaankarakoc** [nestjs/config#1373]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Instead of using ConfigService to construct configurations, it would be nice to be able to do the same thing using decorators also.

### Describe the solution you'd like

```
server:
  port: 3000
  timezone: 'Europe/Istanbul'
```
  
```
@Module({
  imports: [
    ConfigModule.forRoot({
      load: [configuration], // use yaml above or any other file
      watch: true | false // to detect  change and reconstruct config classes
    }),
  ],
})
export class AppModule {} 
```

```
@Configuration()
class ServerConfig {
  @ConfigurationKey('server.port')
  port: number;

  @ConfigurationKey('server.timezone')
  timezone: string;
}
// provide this class to module
```

and use somewhere like

`constructor(private readonly serverConfig: ServerConfig) {}`

### What is the motivation / use case for changing the behavior?

I think decorator based approach is cleaner. And in my company we inject configs dynamically to the pod before application starts then we can change configs without a new deployment when we needed. So capability of detecting change and reconstruct configuration classes using `watch` flag would be useful.

**Comment by micalevisk** [comment]
hi!

I think that this should live as an another package (perhaps a community-made one) as the API is pretty different from what we have in `@nestjs/config`

**Comment by halilkaankarakoc** [comment]
I've already implemented this feature as a separate package, I just thought built-in support would be nice. Thanks for your response :)

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
