### ISSUE TITLE
Optional Registration using the ConfigModule

### ISSUE THREAD

**Issue by jmcdo29** [nestjs/config#1407]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

There arises occasions where we might want to allow for registering a module optionally, I see this come up on the Discord server every now and again. Like running the CronModule in only _one_ running instance based on the env variables, or setting up the serve static in a single instance.

### Describe the solution you'd like

I'd like to propose a new static method on the `ConfigModule`, something like `optionallyRegisterModule` that takes in the module to optionally register, and the environment variable that should be checked against if the module should be registered, **or** a method that returns a boolean for the same reason. If the valueof the key is falsy, or the method returns false, the new method should return a new `NoopModule` which has no imports, exports, providers, or controllers.

This method would be an `async` method that `await ConfigModule.envVariablesLoaded` and then check against `process.env[key]` to ensure that we can properly wait for the environment variables to be loaded and then react accordingly.

### Teachability, documentation, adoption, migration strategy

We mention it in the docs and possibly make a blog article on it

### What is the motivation / use case for changing the behavior?

Optionally registering modules, as described above :)

I'm happy to work on this as well if we like the idea of it.

**Comment by micalevisk** [comment]
can you show some code snippet on how it would looks like fom consumer side?

**Comment by jmcdo29** [comment]
```ts
@Module({
  imports: [
    ConfigModule.forRoot(),
    ConfifgModule.optionallyRegisterModule(
      ScheduleModule.forRoot(),
      'USE_CRON'
    )
  ],
  ...
})
export class AppModule {}
```
**OR**
```ts
@Module({
  imports: [
    ConfigModule.forRoot(),
    ConfifgModule.optionallyRegisterModule(
      ScheduleModule.forRoot(),
      () => JSON.parse(process.env.USE_ENV)
    )
  ],
  ...
})
export class AppModule {}
```

**Comment by micalevisk** [comment]
I wonder if couldn't be something that works on top of `ConfigService`:

```ts
@Module({
  imports: [
    ConfigModule.forRoot(),
    ConfigModule.registerModule({
      module: ScheduleModule.forRoot(),
      when: (configService: ConfigService) =>
        configService.get('USE_ENV') == true
    })
  ],
  ...
})
export class AppModule {}
```

**Comment by jmcdo29** [comment]
Hmmm, I'm not quite sure how feasible that would be, as injecting a provider is _usually_ for module _configuration_, not module _registration_, y'know? But as `imports` can have async values, we can make use of the existing method for waiting for `process.env` to be loaded and return the correct module. I do like the `registerModule` with the object rather than the two parameters though

**Comment by kamilmysliwiec** [comment]
So basically you're suggesting that we could expose this helper type out of the box, as part of the `@nestjs/config` package:

```ts
export class ConditionalModule {
  static async registerWhen(moduleToRegister, condition) {
    await ConfigModule.envVariablesLoaded();
    return condition(process.env) 
         ? { module: ConditionalModule, imports: [moduleToRegister] 
         : { module: ConditionalModule, imports: [] }
  }
}
```

Example

```ts
imports: [ConditionalModule.registerWhen(ScheduleModule.forRoot(), ({ USE_CRON }) => ...)]
```

**Comment by jmcdo29** [comment]
@kamilmysliwiec yep, that's generally it. Figured we'd make it a part of this package as it's very closely tied to the module

**Comment by kamilmysliwiec** [comment]
This would make a lot of sense indeed. Would you like to create a PR for this?

**Comment by jmcdo29** [comment]
Absolutely. I'll work on it this week
