### ISSUE TITLE
Eager loading of dotenv/.env

### ISSUE THREAD

**Issue by PhearZero** [nestjs/config#1413]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Ability to use .env file in decorators by eagerly loading `dotenv` files

### Describe the solution you'd like

Separate the concerns of the `ConfigModule.forRoot` method. This would move the env loading into a public method

```ts
ConfigModule.config(options?) 
```

This would be consumed by forRoot

### Teachability, documentation, adoption, migration strategy

This is a non-breaking change, it just allows users to call ConfigModule.config() and eagerly load the .env file

### What is the motivation / use case for changing the behavior?

env support using ConfigModule in decorators, currently we are calling dotenv directly which leads to confusion on which configuration library to use. This keeps it in Nest.js ecosystem but solves for this particular edge case.

**Comment by jmcdo29** [comment]
What's the benefit of this over just `dotenv.config()`? I see you say "calling dotenv...leads to confusion on which configuration library to use", how would a second way to use the `ConfigModule` change that?

**Comment by PhearZero** [comment]
> What's the benefit of this over just `dotenv.config()`? I see you say "calling dotenv...leads to confusion on which configuration library to use", how would a second way to use the `ConfigModule` change that?

It's not critical at all, just was confusing in the documentation. I found a few responses on StackOverflow with a similar issue. Maybe we could just enhance the documentation to include dotenv?

**Comment by jmcdo29** [comment]
> Maybe we could just enhance the documentation to include dotenv?

I think this would be the better approach. And explain the use case as to when you'd want to call `dotenv` directly vs letting the `ConfigModule` take care of it

**Comment by PhearZero** [comment]
Will update the docs! Thanks!
