### ISSUE TITLE
expandVariables option does not working correctly.

### ISSUE THREAD

**Issue by LNSol** [nestjs/config#1453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

i think expandVariable options is not working correctly when i create a dynamic module using ConfigModule.forRoot().
Because, expandOptions.parsed is overrided

### Minimum reproduction code

https://github.com/LNSol/nest-tutorial/blob/main/src/app.controller.ts

### Steps to reproduce

1. `npm i`
2. `npm run start:dev`
3. `curl http://localhost:3000/env-test`
4. `undefined` is printed.

### Expected behavior

i think loadEnvFile() method in config.module.ts file need to change like this:

```
if (options.expandVariables) {
          const expandOptions: DotenvExpandOptions =
            typeof options.expandVariables === 'object'
              ? options.expandVariables
              : {};
          config =
            expand({ ...expandOptions, parsed: config }).parsed || config;
        }
```

to

```
if (options.expandVariables) {
          const expandOptions: DotenvExpandOptions =
            typeof options.expandVariables === 'object'
              ? options.expandVariables
              : {};
          const parsedInExpandOptions = expandOptions?.parsed;

          config =
            expand({
              ...expandOptions,
              parsed: parsedInExpandOptions
                ? { ...parsedInExpandOptions, ...config }
                : config,
            }).parsed || config;
        }
```

### Package version

3.0.1

### NestJS version

10.0.0

### Node.js version

16.18.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/config/pull/1452
