### ISSUE TITLE
The function 'get' with default value and infer=true still returns undefined

### ISSUE THREAD

**Issue by tomerslice** [nestjs/config#1460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When putting infer=true in the function 'get' you get the value with undefined.
When you add a default value you don't remove the undefined.

### Minimum reproduction code

https://gist.github.com/tomerslice/49e523846129dc8e88a5aa28d536fc4f

### Expected behavior

The type of the undefined should be remove.

### Package version

3.0.1

### NestJS version

10.2.3

### Node.js version

18

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Fixed in 3.1.1
