### ISSUE TITLE
Handle JS runtimes .env autoloading

### ISSUE THREAD

**Issue by andreafspeziale** [nestjs/config#1461]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

While testing Bun JS runtime as drop-in Node.js alternative I noticed some glitches in my project automated tests.

While developing I usually have two `env` files:
- `.env` used to run the application eg. `nest start --watch`
- `env/.env.test` used in the tests by the `ConfigModule` leveraging the `envFilePath` option

Node.js does not load `.env` files automatically. They recently added `.env` file support in the latest versions but a flag would be required ([based on my understanding](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V20.md#built-in-env-file-support)).

Instead Bun will automatically load the `.env` and so at this [config module line](https://github.com/nestjs/config/blob/c44ba757ee91353f25aa70c1283a6f3b3eb7e9cb/lib/config.module.ts#L203) the already present env vars will be ignored. This means that leveraging `envFilePath: join(process.cwd(), 'env/.env.test')` will not produce the aimed configuration object.

The following screenshots should be pretty exhaustive:

<img width="1639" alt="Screenshot 2023-09-14 alle 14 56 29" src="https://github.com/nestjs/config/assets/7680940/00d4a96b-ffa9-4d6d-b465-584828857384">

Same here:

<img width="1636" alt="Screenshot 2023-09-14 alle 14 59 01" src="https://github.com/nestjs/config/assets/7680940/922ac54f-b3f9-45e5-91d3-7e1c42e09032">

While:

<img width="1649" alt="Screenshot 2023-09-14 alle 14 57 34" src="https://github.com/nestjs/config/assets/7680940/3ca6ce5b-b5ef-41de-aad6-2340e2ff2cab">

Btw the same is not happening if actually using the `dotenv` `path` option

The following will return the expected env variables even if in the project root `.env` file exists. It will work even if (e.g) ran with Bun:

<img width="1171" alt="Screenshot 2023-09-14 alle 14 15 35" src="https://github.com/nestjs/config/assets/7680940/2963a0ce-2e26-4a2a-8167-9bd8dc7b0788">

Or even with Node:

<img width="1116" alt="Screenshot 2023-09-14 alle 15 01 14" src="https://github.com/nestjs/config/assets/7680940/5c7e1e04-712d-4b22-b2f0-2a5beaafbdb3">

So at the end of the day `ConfigModule envFilePath` flag is a little bit misleading IMHO. 

### Describe the solution you'd like

All this crap can be mitigated in multiple ways:

- Bun implementing a flag in order to avoid loading by default `.env` 
- Developer not having `.env` in the root and loading it by path in their core module (not huge fan)
- ConfigurationModule new option in order to avoid the "filter" pointed out in the above section

Let me know your thoughts and thanks for your hard work

### What is the motivation / use case for changing the behavior?

Improve developer experience

**Comment by kamilmysliwiec** [comment]
> Instead Bun will automatically load the .env and so at this [config module line](https://github.com/nestjs/config/blob/c44ba757ee91353f25aa70c1283a6f3b3eb7e9cb/lib/config.module.ts#L203) the already present env vars will be ignored.

This is the expected behavior.

> Bun implementing a flag in order to avoid loading by default .env

Could you report this in the Bun repository?

**Comment by andreafspeziale** [comment]
> This is the expected behavior.

As per:

- name of the `ConfigModule envFilePath` option
- the way plain dotenv lib works

I believe that the expected behavior of using `envFilePath` would be this as mentioned in the main PR comment

<img width="1282" alt="Screenshot 2023-09-15 alle 09 47 32" src="https://github.com/nestjs/config/assets/7680940/21ec0665-9fb6-4360-b74c-54ffbe048dfd">

or at least along with some other option to make it happen avoiding breaking changes and keeping the current "implementation/expected behavior" leveraging default.

> Could you report this in the Bun repository?

Sure, I'll see if makes sense to them
