### ISSUE TITLE
ConditionalModule registerWhen support ConfigModule value

### ISSUE THREAD

**Issue by peterLam2** [nestjs/config#1635]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

i would try to use a nested yaml file as the custom config value to control if a module is import or not,
however it allow to use the environment variable.

```
    ConditionalModule.registerWhen(
      DevOnlyEcProductModule,
      (env: NodeJS.ProcessEnv) =>
        env['something.enable'] === true,
    ),
```

### Describe the solution you'd like

It would be good, if this also can be inject a module like following .

```
    ConditionalModule.registerWhenAsync(
      DevOnlyEcProductModule,
      (config: ConfigService) =>
        config.get('something.enable') === true
    ),
```

### What is the motivation / use case for changing the behavior?

can use the custom config instead of rely on the environment variable setting.
Thanks

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
