### ISSUE TITLE
Add generic <KEY> to forRoot and forFeature

### ISSUE THREAD

**Issue by josephkabba** [nestjs/config#1727]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

No it is not a problem.,

### Describe the solution you'd like

I want the `forFeature` and `forRoot` to have a generic type when I call `ConfigModule.forRoot<Keys>({ ... })` the configService's get method only accepts enums of strings of type Keys and not just any string.

### What is the motivation / use case for changing the behavior?

I tried to scope the keys in the `get` method, but it was a difficult process. Our platform's envs have increased in number and we want to keep configs scoped.

**Comment by micalevisk** [comment]
I did not understand the goal

Can you please elaborate on how that generics arg on `ConfigModule` will help you on `ConfigService`?

**Comment by micalevisk** [comment]
I'm pretty sure that this is not possible to achieve with TypeScript.

Feel free to try it out

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
