### ISSUE TITLE
Can retrieve config from other module register with forFeature

### ISSUE THREAD

**Issue by wangcode** [nestjs/config#1771]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Currently I have two module Test and Other both import to AppModule, and have a config file with namespace "database" import to Test module as below
```javascript
//app.module.ts
@Module({
  imports: [ConfigModule.forRoot(), TestModule, OtherModule],
  controllers: [],
})
export class AppModule { }

// config.ts
export const database_config = registerAs('database', () => ({
    host: process.env.DATABASE_HOST,
    port: process.env.DATABASE_PORT
}));

// test.module.ts
@Module({
  imports: [ConfigModule.forFeature(database_config)],
  controllers: [TestController],
  providers: [TestService]
})
export class TestModule { }
```
As my understand, it should only be read in the Test module, But I can retrieve it on Other module as below

```javascript
// other.module.ts
@Module({
  imports: [ConfigModule],
  controllers: [OtherController],
  providers: [OtherService]
})
export class OtherModule { }

// other.service.ts
@Injectable()
export class OtherService {
    constructor(private configService: ConfigService) {
        console.log("other", this.configService.get("database"))
    }
}
```

```console
other { host: 'https://www.google.com', port: '5432' }
```

Currently I can retrieve config from Other service. Is this expected behavior?

### Minimum reproduction code

NA

### Expected behavior

"Other" service can not read

### Package version

3.2.3

### NestJS version

10.0.0

### Node.js version

v22.2.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Thank you for taking the time to submit your report! From the looks of it, this could be better discussed on our Discord. If you haven't already, please join [here](https://discord.gg/nestjs) and send a new post in the #⁠ 🐈 nestjs-help forum. Make sure to include a link to this issue, so you don't need to write it all again. We have a large community of helpful members, who will assist you in getting this to work.
