### ISSUE TITLE
The set method incorrectly updates the variable outside the VALIDATED_ENV_PROPNAME token when updating the validated configuration.

### ISSUE THREAD

**Issue by HenryOoO** [nestjs/config#1815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If you validate a configuration with a default value using joi, then after updating the value using the set method, you will not get a new value again because the set method does not concatenate VALIDATED_ENV_PROPNAME, and will simply place the value that needs to be updated outside of this property.

### Minimum reproduction code

https://stackblitz.com/edit/nestjs-typescript-starter-5pr4dj?file=src%2Fapp.module.ts

### Expected behavior

set to get the latest value

### Package version

3.2.3

### NestJS version

10.3.8

### Node.js version

20.11.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
I believe this is related to this issue https://github.com/nestjs/config/issues/1822
