### ISSUE TITLE
getOrThrow doesn't return Joi parsed values

### ISSUE THREAD

**Issue by leandroluk** [nestjs/config#1835]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Today it is possible to pass a validationSchema using Joi to the config module to validate environment variables. Joi has a great behavior allowing a way to not only validate values ​​but also to change returned values. Unfortunately when ConfigService.getOrThrow is called they do not return parsed values ​​but the original value from the environment.

### Minimum reproduction code

https://gist.github.com/leandroluk/f0132074b6e0b129e54b37e8082f0c96

### Steps to reproduce

1. Create any default nestjs project.

2. Install the `@nestjs/config`.

3. Change the `src/app.module.ts` like this:

```ts
import {Module} from '@nestjs/common';
import {ConfigModule} from '@nestjs/config';
import Joi from 'joi';
import {AppService} from './app.service'

@Module({
  imports: [
    ConfigModule.forRoot({
      validationSchema: Joi.object({
        TEST_ENV: Joi.string().default(' string ').trim()
      }).options({convert: true}),
    }),
  ],
  providers: [AppService],
})
export class AppModule {}
```

4. Change the `src/app.service.ts` like this:

```ts
import {Injectable} from '@nestjs/common';
import {ConfigService} from '@nestjs/config';

@Injectable()
export class AppService {
  constructor(private readonly configService: ConfigService) {
    console.log(this.configService.getOrThrow('TEST_ENV'))
    // expected: "string", result: " string " (doesn't returned the validated and parsed value of Joi
  }
}
```

### Expected behavior

When call ConfigService.getOrThrow it should be return the parsed value from Joi but return the raw value.

### Package version

^3.2.3

### NestJS version

^10.0.0

### Node.js version

v20.17.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
everything is working as expected here.

Please provide a minimum reproduction repository, not just code snippets. You can start one by running `npm init nest` in your terminal

## [why reproductions are required](https://antfu.me/posts/why-reproductions-are-required)
