### ISSUE TITLE
 npm install --save @nestjs/config

### ISSUE THREAD

**Issue by iAmNsengi** [nestjs/config#1898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I am trying to install @nestjs/config but it seems like it doesn't exists anymore.
Read also through the docs and it seems like there is no other fix available: https://docs.nestjs.com/techniques/configuration
Looks like it is not on npm anymore: https://www.npmjs.com/package/@nestjs/config

### Minimum reproduction code

https://github.com/iAmNsengi/nest-blog-backend/tree/main

### Expected behavior

I expect he package to get installed but I am getting:
```bash
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/@nestjs%2fconfig - Not found
npm error 404
npm error 404  '@nestjs/config@*' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
npm error A complete log of this run can be found in: C:\Users\nseng\AppData\Local\npm-cache\_logs\2024-12-08T18_51_45_945Z-debug-0.log
```

### Package version

10.4.7

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by jmcdo29** [comment]
https://github.com/nestjs/nest/issues/14289

**Comment by iAmNsengi** [comment]
> [nestjs/nest#14289](https://github.com/nestjs/nest/issues/14289)

Issue solved, thanks 👍
