### ISSUE TITLE
How does it support multiple env files?

### ISSUE THREAD

**Issue by zhaoyi0113** [nestjs/config#264]
I am looking through this instruction: https://docs.nestjs.com/techniques/configuration to setup env file for my nestjs application. 

I see it supports creating multiple config files: `envFilePath: ['.env.development.local', '.env.development'],` but I wonder how it supports dynamically choose environment file based on NODE_ENV. 

I have three env files: `.env.dev`, `.dev.staging`, `.dev.prod`. And I usually use `NODE_ENV=dev` env to set the current environment. How does `nestjs/dev` work with NODE_ENV. Can it pick one based on its value?

**Comment by kamilmysliwiec** [comment]
> but I wonder how it supports dynamically choose environment file based on NODE_ENV.

For example:
```typescript
envFilePath: `.env.${process.env.NODE_ENV}`
```
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.

**Comment by micalevisk** [comment]
@kamalkech this might help you https://docs.nestjs.com/techniques/configuration#custom-env-file-path

I'm using `envFilePath` with no worries.
