### ISSUE TITLE
Using class-validator for ConfigModule validation

### ISSUE THREAD

**Issue by muturgan** [nestjs/config#318]
## Is your feature request related to a problem? Please describe.
Why i should install additional dependency for only one call?

## Describe the solution you'd like
Can you add an option to validate enviroment variables via class-validator instead of @hapi/joi?

## What is the motivation / use case for changing the behavior?
Well, for example my docker container will be smaller an its building faster. The chance of getting a dependency with a vulnerability is less.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by haritonstefan** [comment]
Hey @kamilmysliwiec I consider giving it a try.
I was wondering why initially the config validation was implemented using joi and not class-validator, where there some specific things that tilted the choice scale towards joi?

**Comment by kamilmysliwiec** [comment]
Before we had the official `@nestjs/config` module, the documentation has shown an example of how to validate config using Joi. We decided that it would make it easier to migrate towards the official module now if we use Joi underneath as well @haritonstefan.

**Comment by Tony133** [comment]
Hey @kamilmysliwiec,  shouldn't this issue be closed since a pull has been made for this problem and also the merge done?

**Comment by kamilmysliwiec** [comment]
Closing right now!
