### ISSUE TITLE
Use dotenv-expand instead of dotenv

### ISSUE THREAD

**Issue by AnandChowdhary** [nestjs/config#405]
## I'm submitting feature request
We should use `dotenv-expand` instead of `dotenv`.

Instead of this:

```ts
import { config } from 'dotenv';
config();
```

We should do this:

```ts
import { config } from 'dotenv';
import dotenvExpand from 'dotenv-expand';
dotenvExpand(config());
```

## Current behavior
We use `dotenv` to fetch configuration from the `.env` file

## Expected behavior
We should switch to using `dotenv-expand`

## What is the motivation / use case for changing the behavior?
Using `dotenv-expand`, we can do this:

```env
DB_PROVIDER = "my-database-provider"
DB_USER = "my-database-user"
DB_PASSWORD = "my-database-password"
DB_HOST = "my-database-host"
DB_POST = 3306
DB_NAME = "my-database-name"
DATABASE_URL = "${DB_PROVIDER}://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_POST}/${DB_NAME}"
```

Currently, we'd have to specify the full `DATABASE_URL`.

**Comment by kamilmysliwiec** [comment]
https://docs.nestjs.com/techniques/configuration#expandable-variables

**Comment by AnandChowdhary** [comment]
Oops, thanks!
