### ISSUE TITLE
Types

### ISSUE THREAD

**Issue by olivinValari** [nestjs/config#566]
![Screen Shot 2021-05-13 at 12 43 00 AM](https://user-images.githubusercontent.com/83770825/118012957-30294c80-b384-11eb-9009-2741367c57e9.png)

How can I fix this. Thanks

**Comment by jmcdo29** [comment]
Looks like `@nestjs/config` isn't installed. Without a reproduction there's no way to tell.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
