### ISSUE TITLE
ConfigService::get is not type-hinting correctly its return value

### ISSUE THREAD

**Issue by ericmorand** [nestjs/config#573]
Consider the following use case:

```ts
const configuration = new ConfigService<{
    FOO: number
}<();

const foo = configuration.get('FOO');

foo?.bar; // should fail; doesn't because foo is inferred as any | undefined
```

It is expected that foo is resolved by TypeScript type checker as a number. But it is actually resolved as `any | undefined`.

`get` should have the following signature:

```ts
    get<P extends keyof K>(propertyPath: P): K[P];
```

**Comment by kamilmysliwiec** [comment]
In the next major release, we'll add the `infer` option allowing you to auto infer type (including cases when the dot notation is used, which is awesome), PR here https://github.com/nestjs/config/pull/493. We couldn't really infer types by default due to backward compatibility

**Comment by ericmorand** [comment]
This V8 sounds so promising!!!

**Comment by ealionel** [comment]
> In the next major release, we'll add the `infer` option allowing you to auto infer type (including cases when the dot notation is used, which is awesome), PR here #493. We couldn't really infer types by default due to backward compatibility

Maybe can we add a "defaultInfer" in the ConfigModule.forRoot so it doesn't break backward compatiblity?

**Comment by kamilmysliwiec** [comment]
Type inference cannot be controlled by setting flags in the configuration as it doesn't happen at runtime
