### ISSUE TITLE
Feature idea: support for .env.*.local by default 

### ISSUE THREAD

**Issue by dscafati** [nestjs/config#601]
Hi, I want to propose this feature.

I see it's a common practice for frameworks to support multiple .env files by default, with specific order of precedence between them.

For example, a regular web app could contain
```
.env
.env.production
.env.development
```

The 3 files are versioned on git, and on each environment (local, prod, etc...) there's an extra *.local file. E.g.
```
.env.local
.env.production.local
.env.developoment.local
```

The order of precedence is

`.env.{ENV}.local` > `.env.{ENV}` > `.env.local` > `.env`

Example nextjs: 
https://nextjs.org/docs/basic-features/environment-variables
https://github.com/vercel/next.js/blob/canary/packages/next-env/index.ts#L82

Example symfony:
https://symfony.com/doc/current/configuration.html#overriding-environment-values-via-env-local
https://github.com/symfony/symfony/blob/46ca50fd843b71ed5fc4517f5d87e04fdfb87768/src/Symfony/Component/Dotenv/Dotenv.php#L109

I'll be happy to implement this on the @nestjs/config package

**Comment by jmcdo29** [comment]
[This is already achievable using custom env file paths](https://docs.nestjs.com/techniques/configuration#custom-env-file-path)

**Comment by dscafati** [comment]
Hi @jmcdo29 thanks for your answer. I see I didn't make my point very clear. What I'm proposing here is to have this behavior by default. Coming from other frameworks I expected this to be the default behavior, not to have to define this myself

**Comment by jmcdo29** [comment]
Hmm, personally I'd rather just keep `.env` as the default, [as is the recommendation of the 12-factor app](https://12factor.net/config) as I understand it, and allow for developers to define if they need extra functionality otherwise. I'm open to hear about the pros of allowing for this kind of configuration, but _I_ generally follow a single `.env` if I can help it

**Comment by kamilmysliwiec** [comment]
As @jmcdo29 pointed out above, this is already doable. The current default behavior mimics the underlying lib's behavior (dotenv) that we use for loading env vars. Currently, there're no plans to change this.
