### ISSUE TITLE
Support injection of config namespaces (myConfig.KEY) in async module registration

### ISSUE THREAD

**Issue by Papooch** [nestjs/config#637]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
Say I define a custom configuration namespace using:
```ts
export const DbConfig = registerAs('database', () => ({
  host: process.env.DATABASE_HOST,
  port: +process.env.DATABASE_PORT || 5432
}));
```

I am then able to inject it inside a service constructor as follows: (given I've registered it in the module using `ConfigModule.forFeature(DbConfig)`)
```ts
constructor(
  @Inject(databaseConfig.KEY)
  private dbConfig: ConfigType<typeof DbConfig>,
) {}
```
And I get full type safety, because I can query the parameters as `this.dbConfig.host`

I would expect to be able to do the same inside async module registration:

```ts
ConfigModule.forFeature(DbConfig), // <- I thought this would make it work, but it does not
MyDatabaseModule.forRootAsync({
    imports: [ConfigModule],
    inject: [DbConfig.KEY],
    useFactory: (dbConfig: ConfigType<typeof DbConfig>) => {
        return {
            host: dbConfig.host,
            port: dbConfig.port,
        };
    },
}),
```
But that fails with:
```
Nest can't resolve dependencies of the MyDatabaseModuleOptions (?).
Please make sure that the argument CONFIGURATION(database) at index [0] is available in the MyDatabaseModule context.
```

## Expected behavior
I would expect that to work and inject the config namespace.

It would be also great to be able to do
```ts
const dbConfig = app.select(ConfigModule).get(DbConfig.KEY)
```

## Minimal reproduction of the problem with instructions
I can provide a minimal reproduction, but I think the issue is apparent.

## What is the motivation / use case for changing the behavior?
The config module is a great way to ensure type safety, but when it comes to this use case, we still have to resort to magic strings with configService.get(). The addition of `{ infer: true }` helps a bit, but the string property access still stays.

The current workaround that I'm using is this, but I don't like it
```ts
MyDatabaseModule.forRootAsync({
    imports: [ConfigModule],
    inject: [ConfigService],
    useFactory: (config: ConfigService) => {
        const dbConfig = config.get<ConfigType<typeof DbConfig>>('database')
        return {
            host: dbConfig.host,
            port: dbConfig.port,
        };
    },
}),
```

## Environment
<pre><code>
@nestjs/core: 7.0.0
@nestjs/config: 0.6.3
</code></pre>

**Comment by kamilmysliwiec** [comment]
Your code is invalid.

```typescript
MyDatabaseModule.forRootAsync({
    imports: [ConfigModule.forFeature(DbConfig)], // <!-- here
    inject: [DbConfig.KEY],
    useFactory: (dbConfig: ConfigType<typeof DbConfig>) => {
        return {
            host: dbConfig.host,
            port: dbConfig.port,
        };
    },
}),
```

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
