### ISSUE TITLE
ignoreEnvFile=true doesn't work

### ISSUE THREAD

**Issue by kuangshp** [nestjs/config#641]
I am in`app.module.ts`the file，I want to load different configuration files depending on the environment

```typescript
import { Module } from '@nestjs/common';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { TypeOrmModule } from '@nestjs/typeorm';
import { TypegooseModule } from 'nestjs-typegoose';
import configuration from './config/configuration';

const IS_DEV: boolean = process.env.NODE_ENV != 'production';
@Module({
  imports: [
    ConfigModule.forRoot({
      envFilePath: IS_DEV
        ? ['.env.development.local', '.env.development']
        : ['.env.development.local', '.env.production'],
      isGlobal: true,
      ignoreEnvFile: true,
      load: [configuration],
    }),
    TypeOrmModule.forRoot(),
  ],
})
export class AppModule {}
```
I have `.env`、`.env.development`、`.env.development.local`、`.env.production`the file in my project.
`.env` my use to typeorm cli。in the ConfigModule use ignoreEnvFile=true ,but project loading `.env` config,not According to my configuration

**Comment by jmcdo29** [comment]
Please provide a [minimum reproduction repository](http://minimum-reproduction.wtf).

**Comment by kuangshp** [comment]
[code address](https://codesandbox.io/s/bold-sound-fdbr4?file=/src/main.ts)

I think the code needs to be changed
```typescript
export class ConfigModule {
  /**
   * Loads process environment variables depending on the "ignoreEnvFile" flag and "envFilePath" value.
   * Also, registers custom configurations globally.
   * @param options
   */
  static forRoot(options: ConfigModuleOptions = {}): DynamicModule {
    let validatedEnvConfig: Record<string, any> | undefined = undefined;
    let config = options.ignoreEnvFile
      ? this.loadEnvFile(options)
      : Object.assign(options, {
          envFilePath: [resolve(process.cwd(), '.env'), Array.isArray(options.envFilePath) ? 
          ...options.envFilePath:
          options.envFilePath
        ],
      });
```

**Comment by kamilmysliwiec** [comment]
The `ignoreEnvVars` configuration disables **the validation of env variables**. I'm aware that the property name is somewhat confusing but we decided to not rename it to avoid introducing breaking changes. Apologies for the confusion!

**Comment by lsantos10** [comment]
Looks like the documentation has not been updated: https://docs.nestjs.com/techniques/configuration#disable-env-variables-loading. It still mentions that `ignoreEnvVars` is to disable loading the configuration.
This is important for creating unit tests and overrride any ENV variable set. 
Is there an alternative for using only locally defined variables instead using the variables from `.ENV`

**Comment by micalevisk** [comment]
@lsantos10 there's no mention on `ignoreEnvVars` on that page
