### ISSUE TITLE
envFilePath field bug

### ISSUE THREAD

**Issue by kuangshp** [nestjs/config#660]
I used this field to distinguish between the development environment and the production environment. I read different configuration files from the local environment, but it didn't work. I ended up reading the.env file, I don't know if I made a mistake or not。

[Online Demo Address](https://codesandbox.io/s/zealous-forest-3fd6f?file=/src/app.module.ts:289-300)

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
