### ISSUE TITLE
Add handler for non existing paths

### ISSUE THREAD

**Issue by rottmann** [nestjs/config#744]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

When we access config by path `config.get('my.path.name', 'default value)` we got no error if the path not exists, e.g. cause on refactor you forgot to change the string.

### Describe the solution you'd like

Adding a callback to handle this e.g. `invalidPath` callback:

```
ConfigModule.forRoot({
  invalidPath: (path, defaultValue) => {
    throw new Error('config path not exists: ' + path)
  }
})
```

Without invalidPath-callback, the default value should be used (as it is now).

With invalidPath-callback, the return-value from the callback should be used. Did the callback not return a value, the default value should be used.

### What is the motivation / use case for changing the behavior?

Find missing paths at runtime.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
