### ISSUE TITLE
Incorrect sequence of calling the function `validate`

### ISSUE THREAD

**Issue by fjodor-rybakov** [nestjs/config#756]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The problem is that the `validate` function is called a second time before using the `AppModule` in app

Log...
```
Call validate
Call validate     
Create app context
Create app
```

### Minimum reproduction code

https://github.com/fjodor-rybakov/nestjs-validate-config

### Expected behavior

The `validate` function should be called a second time only after the app context has been created

Expect log...
```
Call validate     
Create app context
Call validate
Create app
```

### Package version

1.1.5

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please search through some of our old issues on this (this has been discussed several times in the past).
