### ISSUE TITLE
Vulnerability classified as "high" severity in lodash.set dependency

### ISSUE THREAD

**Issue by shaunek** [nestjs/config#791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Snyk has recently flagged a high severity vuln in the lodash.set dependency. Here is Snyk's security bulletin:
https://security.snyk.io/vuln/SNYK-JS-LODASHSET-1320032

The original HackerOne report (https://hackerone.com/reports/864701), seems to indicate that the vulnerability was patched in the main lodash package. However it seems that the lodash.set package hasn't been updated in 5 years so it doesn't have the patch.

It may be a good idea change @nestjs/config to rely on the full lodash package or use some other package. This page indicates that the per-method packages are a thing of the past and won't be maintained: https://lodash.com/per-method-packages

### Minimum reproduction code

https://github.com/shaunek/nestjs-config-lodash.set-vuln

### Steps to reproduce

- Clone demo repo https://github.com/shaunek/nestjs-config-lodash.set-vuln
- Install dependecies with `npm install`
  - Note that the only dependency is the @nestjs/config package
- Run index.js with `node index.js`

Results show that the lodash.set package contains the Prototype Pollution vulnerability
![Screen Shot 2021-12-28 at 11 07 50 AM](https://user-images.githubusercontent.com/1263182/147594583-7d327f33-194a-48e7-a050-6ae9d0909efd.png)
 

### Expected behavior

When the javascript code `set({}, "__proto__[test]", "456");` is called it should not pollute the Object.prototype

### Package version

1.1.5

### NestJS version

n/a

### Node.js version

v16.13.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
> It may be a good idea change `@nestjs/config` to rely on the full lodash package or use some other package

now:

![image](https://user-images.githubusercontent.com/13461315/147595441-4f2089f9-867d-4442-917d-ba0eab24d6d5.png)

then:

![image](https://user-images.githubusercontent.com/13461315/147595448-5500f756-ed24-4c14-90be-ec49e85e3d4a.png)

---

Not sure how  important is that, tho.

**Comment by shaunek** [comment]
Agreed that the extra KBs and download time are downsides to using the full lodash. The problem, as I see it, is that the lodash.set/lodash.get/lodash.has packages are no longer maintained and will not be getting any security patches going forward. And unmaintained open source dependencies aren't really acceptable to most companies such as mine.

Some options in my view are
1. Use full lodash
1. Use custom functions which replicate the set/get methods of lodash
1. Use alternative packages that have the same functionality as lodash set/get. For example https://www.npmjs.com/package/dset and https://www.npmjs.com/package/dlv could be alternatives that are small enough
1. Change functionality so that the special dot notation provided by lodash get/set is no longer an option

The easiest to do seems option 1. To me the second most appealing would be option 3, but I'm not sure what appetite the nestjs org has for depending on relatively new packages.

**Comment by micalevisk** [comment]
yeah, at the moment **1** is the safest & easiest.

---

I didn't find any alternative to [`lodash.has`](https://lodash.com/docs/4.17.15#has) besides this "native" one: https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_has that might not be a drop-in replacement

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/config/pull/792
