### ISSUE TITLE
For what reason that I can still access namespaced config via configService from another module even through I have partially register the config?

### ISSUE THREAD

**Issue by iminif** [nestjs/config#807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

For what reason that I can still access namespaced config via configService from other module even through I have partially register the config?

### Minimum reproduction code

https://github.com/iminif/nestjs-config-min

### Steps to reproduce

1. `yarn install`
2. `yarn run start:dev`
3. See output message from terminal console

### Expected behavior

Nothing for featured configurations should be accessed from another module via ConfigService!

### Package version

1.1.6

### NestJS version

8.0.9

### Node.js version

17.3.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Other

![WeChat Screenshot_20220110205811](https://user-images.githubusercontent.com/14133753/148770907-9a54bd32-4536-413b-a5c4-25534d647d2a.png)

**Comment by kamilmysliwiec** [comment]
This is the expected behavior.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
