### ISSUE TITLE
Unable to use referenced `NodeJS.ProcessEnv` type in ConfigService 

### ISSUE THREAD

**Issue by n1md7** [nestjs/config#845]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I try to pass a generic type definition in `ConfigService` then `config.get('NAME', {infer: true})` results an error. 

Although it works with defined types or interfaces it gives an error when a global type `NodeJS.ProcessEnv` is specified 😑. 

To give more details about the issue, I'm using a 3rd party [library](https://www.npmjs.com/package/gen-env-types) to generate a type declaration for env variables. Which is saved in `src/env.d.ts` under global namespace `NodeJS` with the interface `ProcessEnv`. 

Since there are already type declarations I'd like to reference them instead of duplicating the values. 

Like this way
```typescript
constructor(private readonly config: ConfigService<NodeJS.ProcessEnv>) {
    this.configuration = {
      redisHost: config.get('REDIS_HOST', { infer: true })
    };
  }
```

However, when `{infer: true}` is specified ts is complaining with the following output
```bash
src/app.service.ts:10:18 - error TS2769: No overload matches this call.
  Overload 1 of 4, '(propertyPath: never, options: ConfigGetOptions): string', gave the following error.
    Argument of type 'string' is not assignable to parameter of type 'never'.
  Overload 2 of 4, '(propertyPath: keyof ProcessEnv, defaultValue: string): string', gave the following error.
    Argument of type '{ infer: boolean; }' is not assignable to parameter of type 'string'.

10       redisHost: config.get('REDIS_HOST', { infer: true }),
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

Isn't it supposed to work with global types as well?  🤔

### Minimum reproduction code

https://github.com/n1md7/nestjs-config-bug-reproduction

### Steps to reproduce

1. `npm i`
2. `npm run start:dev`

Should output TS error

### Expected behavior

I expected that this code fragment below would work without TS error and would check property path names according to the type instructions.

```typescript
@Injectable()
export class AppService {
  constructor(private readonly config: ConfigService<NodeJS.ProcessEnv>) {
    const host = config.get('REDIS_HOST', { infer: true });
  }
}
```

### Package version

1.1.6

### NestJS version

8.0.0

### Node.js version

16.13.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

I use **IntelliJ IDEA 2021.2.3 (Ultimate Edition)**
npm v8.1.0

Screenshot of TS error highlighting
![image](https://user-images.githubusercontent.com/6734058/152251236-e3d78459-5f00-4ce6-ae4d-a674668e7ae1.png)

**Comment by micalevisk** [comment]
this might be due to some limitation(?) of TS because:

![image](https://user-images.githubusercontent.com/13461315/152607763-55f9f687-6b36-405a-b7d4-c1d66962595e.png)

Even if we didn't specify `include`/`exclude`/`types`, which means that every `.d.ts` will be included, it doesn't work because `keyof T extends string` below will be `false`

https://github.com/nestjs/config/blob/70839014e22e00b99c3fc77f1118efa5d5c6009b/lib/types/path-value.type.ts#L12-L16

**Comment by n1md7** [comment]
Is there any possible workaround for it? or we just need to accept that it doesn't work this way?

**Comment by micalevisk** [comment]
I didn't find any workaround :/

I didn't use `process.env.` directly so I don't need to define that `NodeJS.ProcessEnv` interface

**Comment by kamilmysliwiec** [comment]
I'm guessing defining a new interface that extends the `NodeJS.ProcessEnv` should fix this issue?

**Comment by n1md7** [comment]
I tried but it didn't work unfortunately 😞

![image](https://user-images.githubusercontent.com/6734058/152762516-f7cf21c8-bf11-4ced-ae12-c878f9da08c1.png)

**Comment by kamilmysliwiec** [comment]
There's not much we can do on our side, unfortunately. Check out this issue https://github.com/nestjs/config/issues/749#issuecomment-977654153, specifically this section:

> That means we'd have to add extends Record<string, unknown constraint to the ConfigService type argument but as @micalevisk you pointed out, interfaces don't extend Record type https://github.com/microsoft/TypeScript/issues/42825#issuecomment-780160383 so that would be even a bigger breaking change.
