### ISSUE TITLE
configService.get() cannot get nested custom configuration object properties

### ISSUE THREAD

**Issue by GO-DIE** [nestjs/config#849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

configService.get() cannot get nested custom configuration object properties.
![image](https://user-images.githubusercontent.com/38709773/152651462-9f159c76-4cc7-457c-9736-c905b47fb65c.png)

![image](https://user-images.githubusercontent.com/38709773/152651518-6caad288-103e-462b-8fad-5c6b2998cca2.png)

Does not match the document description
![image](https://user-images.githubusercontent.com/38709773/152668136-cf5c80ba-08aa-4678-bf7d-c17242e34d0a.png)

### Minimum reproduction code

https://github.com/GO-DIE/nestjs

### Steps to reproduce

npm i
npm run start:local:watch

### Expected behavior

normal running!

### Package version

1.1.6

### Node.js version

16.0.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
can you please provide steps to reproduce that?

I ran

```bash
npm ci
npm run start:dev
```

**Comment by GO-DIE** [comment]
> can you please provide steps to reproduce that?
> 
> I ran
> 
> ```shell
> npm ci
> npm run start:dev
> ```

 ```shell
 npm i
 npm run start:local:watch
 ```

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
