### ISSUE TITLE
Allowing validate partial registration like what we do in `ConfigModule.forRoot`

### ISSUE THREAD

**Issue by kasir-barati** [nestjs/config#851]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I think it not clean to propagate a simple validation into multiple places (Some validations in factory and some validations in `env.validate.ts`) and in different ways (Using Joi in partial and using class-validators for the `AppModule`). As you said in this issue: [ValidationSchema does not respect configuration provided to load #311](https://github.com/nestjs/config/issues/311)

> You can put the validation logic directly in the factory.

And in this issue [Add the validationSchema option to the forFeature #209](https://github.com/nestjs/config/issues/209#issuecomment-1032241077)

> This is not how it's supposed to work. The validationSchema is used to validate the env variables, either predefined system vars or these loaded from the .env file. The forFeature() allows registering partial configurations which can include a custom validation mechanism (and defaults applied) by itself anyway.

### Describe the solution you'd like

I prefer to separate concerns as we have `validate` option in the `ConfigModule.forRoot()`. I am using `class-validator` to validate my configs and if I want to have the same thing in the **Partial registration** I would like to do it **like** this: 

```ts
// logger.module.ts
import { Module } from '@nestjs/common';
import { ConfigModule } from '@nestjs/config';

import loggerConfig from './logger.config';
import { validate } from './validators/env.validator';
import { LoggerService } from './logger.service';

@Module({
    // config factory
    imports: [
        ConfigModule.forFeature({
            envFilePath: ['.env'],
            load: [loggerConfig],
            cache: true,
            validate,
        }),
    ],
    providers: [LoggerService],
    exports: [LoggerService],
})
export class LoggerModule {}
```

```ts
// logger.config.ts
import { registerAs } from '@nestjs/config';

import { LoggerConfig } from './logger.type';

export default registerAs(
    'loggerConfig',
    (): LoggerConfig => ({
        level: process.env.LOGGER_LEVEL,
        isRotateLoggerFilesActivated:
            process.env.IS_ROTATE_LOGGER_FILES_ACTIVATED,
        loggerMaxFile: process.env.LOGGER_MAX_FILES,
        loggerMaxSize: process.env.LOGGER_MAX_SIZE,
        loggerName: process.env?.LOGGER_NAME ?? 'you-say',
    }),
);
```

```ts
// ./validators/env.validator.ts
import { plainToInstance } from 'class-transformer';
import {
    IsBoolean,
    IsEnum,
    IsOptional,
    IsString,
    validateSync,
} from 'class-validator';

import { WinstonDefaultLogLevels } from '../logger.type';
import {
    is_rotate_logger_files_activated_should_be_boolean,
    logger_max_files_should_be_string,
    logger_max_size_should_be_string,
    logger_level_is_invalid,
    logger_name_should_be_string,
} from '../contracts/other-errors/error-codes.json';
import { required_environment_variables_loading_failed } from '@you-say/src/shared/contracts/other-errors/error-codes.json';

export class LoggerEnvironmentVariables {
    @IsEnum(WinstonDefaultLogLevels, {
        message: logger_level_is_invalid,
    })
    LOGGER_LEVEL: WinstonDefaultLogLevels;

    @IsOptional()
    @IsString({ message: logger_max_size_should_be_string })
    LOGGER_MAX_SIZE: string;

    @IsOptional()
    @IsString({ message: logger_max_files_should_be_string })
    LOGGER_MAX_FILES: string;

    @IsBoolean({
        message: is_rotate_logger_files_activated_should_be_boolean,
    })
    IS_ROTATE_LOGGER_FILES_ACTIVATED: boolean;

    @IsString({ message: logger_name_should_be_string })
    LOGGER_NAME?: string;
}

export function validate(config: Record<string, unknown>) {
    const validatedConfigs = plainToInstance(
        LoggerEnvironmentVariables,
        config,
        { enableImplicitConversion: true },
    );
    const validatedConfigsErrors = validateSync(validatedConfigs, {
        skipMissingProperties: false,
    });

    if (validatedConfigsErrors.length > 0) {
        console.dir({
            errors: validatedConfigsErrors.map((error) => ({
                value: error.value,
                property: error.property,
                message: Object.values(error.constraints!)[0],
            })),
            errorCode: required_environment_variables_loading_failed,
            message:
                'Application could not load required environment variables',
        });
        throw new Error(validatedConfigsErrors.toString());
    }

    return validatedConfigs;
}
```

Because:
- I can reuse my logger module in multiple projects just by copy and paste without any concern about configs
- Every module knows how to config and validate its configs.

BTW I think putting validation in factory force me to use `joi` over the `class-validator`. Why? because of the same reason we add class-validator validation functionality for the `ConfigModule` due to [this issue](https://github.com/nestjs/config/issues/318)

### What is the motivation / use case for changing the behavior?

- Each module knows how to handle its configs and validate them.
- You do not need more dependency for sake of validating configs (You do not need Joi anymore): If I install Joi I just use it in one case, validating factory configs.
- You have the same validation code for configs everywhere

**Comment by kamilmysliwiec** [comment]
> BTW I think putting validation in factory force me to use joi over the class-validator.

This isn't correct. 

As I've already mentioned here https://github.com/nestjs/config/issues/311#issuecomment-667898251, you should put validation logic for partial registration directly in factories. Factories were designed to contain validation logic.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
