### ISSUE TITLE
Dotenv-expand breaking change 

### ISSUE THREAD

**Issue by DzixxxVizlib** [nestjs/config#882]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Potential Commit/PR that introduced the regression

https://github.com/nestjs/config/commit/f9b62b57683d6cf190becf139c4b4fee75692bba

### Versions

1.1.7 -> 1.2.0

### Describe the regression

Hi again! 😂 
Not sure how many developers are using regexp in env variables but after bumping to 1.2.0 we started facing that issue https://github.com/motdotla/dotenv-expand/issues/65 it required alignments in our infrastructure (`/^someRegExp$/` to `/^someRegExp\$/`) which shouldn't happen in minor release -> can we make a deal and downgrade dotenv-expand and bump it in v.2.0.0 ?

### Minimum reproduction code

```ts

```

### Expected behavior

We shouldn't change regexp envs in minor version bumping ;)

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue? :)

**Comment by kamilmysliwiec** [comment]
Correct :)

**Comment by DzixxxVizlib** [comment]
Give me an hour and I will fix it

**Comment by DzixxxVizlib** [comment]
Perfect timing -> before meeting 😂  v2.0.0 after :D

**Comment by DzixxxVizlib** [comment]
tracking here https://github.com/nestjs/config/pull/883
