### ISSUE TITLE
dotenv-expand loads from process.env even when ignoreEnvVars is true

### ISSUE THREAD

**Issue by Toilal** [nestjs/config#890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using both `ignoreEnvVars: true` and `expandVariables: true` dotenv-expand` still load configuration from environment variables.

### Minimum reproduction code

https://github.com/Toilal/nest-config-ignore-env-vars-repro

### Steps to reproduce

1. Clone the repository
2. npm install
3. MY_VAR=KO npm run start:dev
4. https://localhost:3000

### Expected behavior

This should display OK, but KO is displayed. This means the environment variable is loaded from `process.env` with the following config.

```
imports: [ConfigModule.forRoot({
  expandVariables: true,
  ignoreEnvVars: true
})],
```

### Package version

1.2.0

### NestJS version

8.2.3

### Node.js version

16

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/config/issues/245#issuecomment-646593207
