### ISSUE TITLE
`ConfigService#get` error 'Type instantiation is excessively deep and possibly infinite' when using `any`

### ISSUE THREAD

**Issue by micalevisk** [nestjs/config#906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

this might be related with #625

When we supply some interface that has some prop with `any` to `ConfigService` generics, we got this `tsc` error:

```
TS2589: Type instantiation is excessively deep and possibly infinite
```

For instance:

```ts
// configuration.ts
export interface IConfig {
  foo: string
  // The following line introduces the TS error:
  bar: any
}
export default (): IConfig => ({
  foo: 'bar',
  bar: 123,
});
```

```ts
// app.service.ts
import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import type { IConfig} from './configuration';

@Injectable()
export class AppService {
  constructor(private readonly configService: ConfigService<IConfig, true>) {}
  getFoo(): string {
    return this.configService.get('foo', { infer: true });
  }
}
```

![image](https://user-images.githubusercontent.com/13461315/160267693-7d587948-566b-48e9-8354-80c971090208.png)

### Minimum reproduction code

https://gitlab.com/micalevisk/nestjs-config-issue-906

### Steps to reproduce

read the `README` of the repro above.

### Expected behavior

build the code with no typing errors.

### Package version

2.0.0

### NestJS version

8.4.3

### Node.js version

16.13.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

- `typescript` version: 4.6.3 (the latest one)

I believe this is related with this type alias:

https://github.com/nestjs/config/blob/9f6f2143f3abbe9f6978e9031c978bedc7582309/lib/types/path-value.type.ts#L12-L16

**Comment by micalevisk** [comment]
This is due to this behavior of TS:

```ts
interface Good {
  foo: string
  bar: number
}

type A = Good[keyof Good]
//   ^? type A = string | number

interface Bad {
  foo: string
  bar: any
}

type B = Bad[keyof Bad]
//   ^? type B = any
```

and `any` is basically what's the `T[Key]` ends up being below:

https://github.com/nestjs/config/blob/9f6f2143f3abbe9f6978e9031c978bedc7582309/lib/types/path-value.type.ts#L1-L8

which makes that `T[Key] extends Record<string, any>` always `true`

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/config/pull/907
