### ISSUE TITLE
forFeature Not working properly

### ISSUE THREAD

**Issue by all2pie** [nestjs/config#947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

ConfigModule is overriding other configurations despite using the forFeature method for registration.

Currently the Output is: 

```
Module ==================== A
Module ==================== A
Module ==================== A
```

### Minimum reproduction code

https://github.com/all2pie/nestjs-config-bug

### Steps to reproduce

1. `npm run start:dev` 
2. check logs

### Expected behavior

ConfigModule should not override other configurations when using the forFeature method for registration.

Output should be: 

```
Module ==================== A
Module ==================== B
Module ==================== C
```

### Package version

^2.0.1

### NestJS version

8.2.2

### Node.js version

16.14.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
This is the expected behavior.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
