### ISSUE TITLE
ts second args dont working

### ISSUE THREAD

**Issue by productdevbook** [nestjs/config#956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

![image](https://user-images.githubusercontent.com/38668796/171696834-793a46cf-6f3f-467d-a31d-d883e6db469c.png)

### Minimum reproduction code

https://github.com/productdevbook/nestjs_bug

### Steps to reproduce

1. yarn install
2. go to vscode app.service.ts
3.  
![image](https://user-images.githubusercontent.com/38668796/171697207-ce77b5da-9df9-40f5-91dc-e50f9410d8c8.png)

### Expected behavior

`jwt.private` etc typescript see. But dont see

### Package version

2.1.0

### NestJS version

8.4.6

### Node.js version

v16.15.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by micalevisk** [comment]
indeed. The type inference from `ConfigService` doesn't work with the latest version of `typescript` (v4.7), but it does in v4.6. Here's the demo of such:

https://user-images.githubusercontent.com/13461315/171713700-d38a9f2a-1b24-4f4d-bc4b-9b222ffddd85.mp4

**Comment by kamilmysliwiec** [comment]
So it seems that the feature itself works as expected but the auto-complete is no longer useful, at least that's what I reproduced

**Comment by micalevisk** [comment]
yeah

I read the whole https://devblogs.microsoft.com/typescript/announcing-typescript-4-7 but I still didn't understand why that didn't work anymore. Maybe it's related with [Stricter Checks with Template String Expressions](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#stricter-checks-with-template-string-expressions)

**Comment by micalevisk** [comment]
I found another type utility for the dot notation type inference [here](https://stackoverflow.com/a/71442049/5290447)

It does work but I didn't manage to make it work with `ConfigService` yet

![image](https://github.com/nestjs/config/assets/13461315/dc23f8fc-c961-4a6e-8253-4259afe95172)

**Comment by baconcheese113** [comment]
Thanks for all your work on this @micalevisk 

Is there any chance of making `infer: true` the default value? Using dot-notation through a string value with autocomplete is a neat feature, but I wonder if it's worth the months of tech debt on this. It would be nice to simplify the interface to just
```
constructor(
    private readonly configService: ConfigService<AppConfig>,
) {
    const database = configService.get('database');
}
```

And still have `database` be typed correctly as an object with `nested` and `port`

**Comment by micalevisk** [comment]
@baconcheese113 it would introduce a breaking change. But yeah, we could change that in the next major release. I don't know why it is not the default behavior, tbh

**Comment by baconcheese113** [comment]
Oh additionally, we already validate the runtime value of our config object when registering the ConfigModule. 

So it would be nice if `configService.get` would narrow the type based off the generic parameter instead of assuming all values can be undefined if not called with `getOrThrow`, maybe through some config we can provide to the ConfigModule?

**Comment by micalevisk** [comment]
@baconcheese113 that's not feasible in TS, if I understood you correctly

Please use our Discord server to discuss about it or others requests if you want to.

**Comment by micalevisk** [comment]
I just tested with the latest version of typescript (5.5.x) and it's working again. So I guess we can close this now :)

[demo.webm](https://github.com/nestjs/config/assets/13461315/66d2d3f4-5d05-481f-a865-5303f9ce26cd)
