### ISSUE TITLE
Ability to handle Multiple Configurations 

### ISSUE THREAD

**Issue by all2pie** [nestjs/config#968]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Related to this: https://github.com/nestjs/config/issues/947

### Describe the solution you'd like

The config module could take another optional parameter like `moduleName`  to be used as a token for dependency injection

### What is the motivation / use case for changing the behavior?

I want to do database seeding in microservices.
Every service has different database configurations which I want to import all in a separate seeding microservice to pass them to mongoose.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
